on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BOTK }}
       -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{github.actor}}/echobot:latest
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: student
          password: ${{ secrets.SSH }}
          script: |
            echo ${{secrets.BOTK}} | docker login --username ${{github.actor}} --password -stdin ghcr.io
            docker run --rm --detach ghcr.io/${{github.actor}}/echobot:latest